name: commit
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  validate:
    uses: $/.github/workflows/validate.yml
  deploy-staging:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployed to staging!"
  deploy-production:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployed to production!"
