name: tag
on:
  push:
    tags:
      - v*
jobs:
  validate:
    uses: $/.github/workflows/validate.yml
  deploy-production:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployed in prod!"
